### ISSUE TITLE
Minor issues with documentation for Amplitude Amplification 

### ISSUE THREAD

**Issue by ntezak** [rigetticomputing/grove#80] opened 2017-10-11 16:10 UTC
The description of the oracle `U_w` is wrong.
```python
def amplify(A, A_inv, U_w, qubits, num_iter, init=True):
    """
[...]
    :param U_w: an oracle maps any basis vector to either |0> or |1>
[...]
    """
```

There are also a few typos.

**Comment by jotterbach** [comment] 2017-10-11 16:40
closing this as a dupe of #81

**Closed by jotterbach** 2017-10-11 16:40 UTC
