### ISSUE TITLE
grover.py should distinguish SyncConnection from JobConnection

### ISSUE THREAD

**Issue by ogamel** [rigetticomputing/grove#99] opened 2017-11-08 16:58 UTC
In grover.py, the line    
        `      sampled_bitstring = cxn.run_and_measure(self.grover_circuit, self.qubits)[0]`

works ok when cxn is a SyncConnection, but when cxn in a JobConnection I get 
> TypeError: 'JobResult' object does not support indexing

It worked when I replaced it with this code
``` 
        import pyquil.api as api # added for type check

        if type(cxn) is api.SyncConnection:
            sampled_bitstring = cxn.run_and_measure(self.grover_circuit, self.qubits)[0]
        elif type(cxn) is api.JobConnection:
            res=cxn.run_and_measure(self.grover_circuit, self.qubits)
            import time

            while not res.is_done():
                time.sleep(1)
            sampled_bitstring=res.decode()[0]
        else:
            assert False, "connection object of unidentified type"
```

Either that, or perhaps the SyncConnection and JobConnection objects should be redesigned to have the same structure to avoid having to check the type of connection (a requirement that likely will not scale well)

-As an aside, both Sync and Job Connections can at most execute Grover's algorithm for a 7 bit number. When I try 8 bit string e.g. '10001000', I get a 
> HTTPError: 413 Client Error: Request Entity Too Large for url: https://job.rigetti.com/beta/job

Why doesn't the Job connection (with 25 qubits) have a higher capacity than the sync (with 16)?

**Comment by jotterbach** [comment] 2017-11-08 17:23
Thanks for reporting @ogamel . We'll have a look!

**Comment by stevenheidel** [comment] 2017-11-08 17:51
Great suggestions! We've seen this issue a couple times and will be changing PyQuil to make it easier to work with: https://github.com/rigetticomputing/pyquil/issues/161

**Comment by ogamel** [comment] 2017-11-08 20:33
Thanks.
Any idea why the second issue occurs? Namely getting the following error anytime I use a string of more than 7 bits:

> HTTPError: 413 Client Error: Request Entity Too Large for url: https://job.rigetti.com/beta/job

In theory I should be able to search 16-bit and 25-bit strings on Sync and Job Connections respectively, but both crash as above for 8+.

**Comment by stevenheidel** [comment] 2017-11-09 00:29
How big is the circuit that you're sending? Can you print the results of `.out()` on the program before you send it to the QVM?

**Comment by ogamel** [comment] 2017-11-09 14:30
I am executing a modified version from the provided Jupyter example for Grover's algorithm:

```
from grove.amplification.grover import Grover

target_bitstring = '10001000'
bit = ("0", "1")
bitstring_map = {}
target_bitstring_phase = -1
nontarget_bitstring_phase = 1

# We construct the bitmap for the oracle
for bitstring in product(bit, repeat=len(target_bitstring)):
    bitstring = "".join(bitstring)
    if bitstring == target_bitstring:
        bitstring_map[bitstring] = target_bitstring_phase
    else:
        bitstring_map[bitstring] = nontarget_bitstring_phase

# Execute Grover's algorithm
found_bitstring=Grover().find_bitstring(qvm,bitstring_map)
```

when the target_bitstring is 8+ bits I get the aforementioned error, whether with a Sync or Job Connection. Otherwise it works fine.

**Comment by stevenheidel** [comment] 2017-11-09 19:03
The program that gets sent to Forest is almost 5MB which won't be supported by any server. I think the circuit that Grover() is generated is simply too big, it's also quite inefficient (I don't think this is your fault, I think the problem is in the library itself). For example, the circuit contains hundreds of copies of these lines:
```
DEFGATE C-NOT:
    1.0, 0.0, 0.0, 0.0
    0.0, 1.0, 0.0, 0.0
    0.0, 0.0, 0.0, 1.0
    0.0, 0.0, 1.0, 0.0
```

First, CNOT is already in the standard gate set and second, there's no need to define a gate more than once. Here's the code I used to print the circuit:

```python
from grove.amplification.grover import Grover
from itertools import product
from pyquil.api import SyncConnection

qvm = SyncConnection()

target_bitstring = '10001000'
bit = ("0", "1")
bitstring_map = {}
target_bitstring_phase = -1
nontarget_bitstring_phase = 1

# We construct the bitmap for the oracle
for bitstring in product(bit, repeat=len(target_bitstring)):
    bitstring = "".join(bitstring)
    if bitstring == target_bitstring:
        bitstring_map[bitstring] = target_bitstring_phase
    else:
        bitstring_map[bitstring] = nontarget_bitstring_phase

# Execute Grover's algorithm
grover = Grover()
grover._init_attr(bitstring_map)
print(grover.grover_circuit.out())
# found_bitstring=Grover().find_bitstring(qvm,bitstring_map)
```

@jotterbach - could you take a look at the above?

**Comment by ogamel** [comment] 2017-11-09 19:56
Thanks Steven, let

**Comment by jotterbach** [comment] 2017-11-09 19:57
Will take a look @ogamel @stevenheidel

**Comment by ogamel** [comment] 2017-11-16 18:02
Hey @jotterbach and @stevenheidel , any luck with this?
Thanks

**Comment by jotterbach** [comment] 2017-11-18 01:53
@ogamel I attached a link to the plain quil code that is coming out of you example code above. As you can see you try to `degate` a 256x256 matrix which is too big (also there a lot of other `defgate`s). This is a result of the implementation of Grover we have right now, which does not support too many qubits as it's meant to be educational.

[large_grover.quil](https://github.com/rigetticomputing/grove/files/1484264/large_grover.txt)

@ampolloreno can you have a look why we are `DEFGATE`ing so many `CNOT`s? Let's figure out why we have so many gates (apart from the oracle).

**Comment by ampolloreno** [comment] 2017-11-20 18:02
Hello folks, sorry for the delayed response. I'm looking into all of this now. Likely the `defgate` are arising from decomposing a many-qubit-controlled gate (I think in this case, the diffusion operator probably is being decomposed). This isn't necessary if we're not actually running on hardware, so I'll figure out where this is happening, and replace it a single defgate.

On the other hand, this isn't going to help anything if just `defgate-ing` a single matrix for 8 qubits is too large, in fact then it seems we *should* be recursively defining these gates into circuits of smaller gates. 

For anyone interested, the reason it is defined `CNOT` is because it's just recursively defining controlled gates to compose a larger gate. It wasn't checking to see if any were defined already. This could/should be smarter.  

I'll see what  I can do.

**Closed** 2018-01-03 17:42 UTC
Labels: bug
